// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: castmer.proto

package castmerservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SingUpData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Lasname       string                 `protobuf:"bytes,3,opt,name=lasname,proto3" json:"lasname,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingUpData) Reset() {
	*x = SingUpData{}
	mi := &file_castmer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingUpData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingUpData) ProtoMessage() {}

func (x *SingUpData) ProtoReflect() protoreflect.Message {
	mi := &file_castmer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingUpData.ProtoReflect.Descriptor instead.
func (*SingUpData) Descriptor() ([]byte, []int) {
	return file_castmer_proto_rawDescGZIP(), []int{0}
}

func (x *SingUpData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SingUpData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SingUpData) GetLasname() string {
	if x != nil {
		return x.Lasname
	}
	return ""
}

func (x *SingUpData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SingUpData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SingUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingUpResponse) Reset() {
	*x = SingUpResponse{}
	mi := &file_castmer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingUpResponse) ProtoMessage() {}

func (x *SingUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castmer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingUpResponse.ProtoReflect.Descriptor instead.
func (*SingUpResponse) Descriptor() ([]byte, []int) {
	return file_castmer_proto_rawDescGZIP(), []int{1}
}

func (x *SingUpResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type LoginData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginData) Reset() {
	*x = LoginData{}
	mi := &file_castmer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginData) ProtoMessage() {}

func (x *LoginData) ProtoReflect() protoreflect.Message {
	mi := &file_castmer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginData.ProtoReflect.Descriptor instead.
func (*LoginData) Descriptor() ([]byte, []int) {
	return file_castmer_proto_rawDescGZIP(), []int{2}
}

func (x *LoginData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_castmer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_castmer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_castmer_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_castmer_proto protoreflect.FileDescriptor

const file_castmer_proto_rawDesc = "" +
	"\n" +
	"\rcastmer.proto\x12\acastmer\"|\n" +
	"\n" +
	"SingUpData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\alasname\x18\x03 \x01(\tR\alasname\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\",\n" +
	"\x0eSingUpResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse\"=\n" +
	"\tLoginData\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\"+\n" +
	"\rLoginResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse2\x84\x01\n" +
	"\x15ClientHandlingService\x126\n" +
	"\x06SignUp\x12\x13.castmer.SingUpData\x1a\x17.castmer.SingUpResponse\x123\n" +
	"\x05Login\x12\x12.castmer.LoginData\x1a\x16.castmer.LoginResponseB\x12Z\x10./castmerserviceb\x06proto3"

var (
	file_castmer_proto_rawDescOnce sync.Once
	file_castmer_proto_rawDescData []byte
)

func file_castmer_proto_rawDescGZIP() []byte {
	file_castmer_proto_rawDescOnce.Do(func() {
		file_castmer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_castmer_proto_rawDesc), len(file_castmer_proto_rawDesc)))
	})
	return file_castmer_proto_rawDescData
}

var file_castmer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_castmer_proto_goTypes = []any{
	(*SingUpData)(nil),     // 0: castmer.SingUpData
	(*SingUpResponse)(nil), // 1: castmer.SingUpResponse
	(*LoginData)(nil),      // 2: castmer.LoginData
	(*LoginResponse)(nil),  // 3: castmer.LoginResponse
}
var file_castmer_proto_depIdxs = []int32{
	0, // 0: castmer.ClientHandlingService.SignUp:input_type -> castmer.SingUpData
	2, // 1: castmer.ClientHandlingService.Login:input_type -> castmer.LoginData
	1, // 2: castmer.ClientHandlingService.SignUp:output_type -> castmer.SingUpResponse
	3, // 3: castmer.ClientHandlingService.Login:output_type -> castmer.LoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_castmer_proto_init() }
func file_castmer_proto_init() {
	if File_castmer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_castmer_proto_rawDesc), len(file_castmer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_castmer_proto_goTypes,
		DependencyIndexes: file_castmer_proto_depIdxs,
		MessageInfos:      file_castmer_proto_msgTypes,
	}.Build()
	File_castmer_proto = out.File
	file_castmer_proto_goTypes = nil
	file_castmer_proto_depIdxs = nil
}
