// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: castmer.proto

package castmerservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientHandlingService_SignUp_FullMethodName = "/castmer.ClientHandlingService/SignUp"
	ClientHandlingService_Login_FullMethodName  = "/castmer.ClientHandlingService/Login"
)

// ClientHandlingServiceClient is the client API for ClientHandlingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientHandlingServiceClient interface {
	SignUp(ctx context.Context, in *SingUpData, opts ...grpc.CallOption) (*SingUpResponse, error)
	Login(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*LoginResponse, error)
}

type clientHandlingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientHandlingServiceClient(cc grpc.ClientConnInterface) ClientHandlingServiceClient {
	return &clientHandlingServiceClient{cc}
}

func (c *clientHandlingServiceClient) SignUp(ctx context.Context, in *SingUpData, opts ...grpc.CallOption) (*SingUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SingUpResponse)
	err := c.cc.Invoke(ctx, ClientHandlingService_SignUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientHandlingServiceClient) Login(ctx context.Context, in *LoginData, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, ClientHandlingService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientHandlingServiceServer is the server API for ClientHandlingService service.
// All implementations must embed UnimplementedClientHandlingServiceServer
// for forward compatibility.
type ClientHandlingServiceServer interface {
	SignUp(context.Context, *SingUpData) (*SingUpResponse, error)
	Login(context.Context, *LoginData) (*LoginResponse, error)
	mustEmbedUnimplementedClientHandlingServiceServer()
}

// UnimplementedClientHandlingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientHandlingServiceServer struct{}

func (UnimplementedClientHandlingServiceServer) SignUp(context.Context, *SingUpData) (*SingUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUp not implemented")
}
func (UnimplementedClientHandlingServiceServer) Login(context.Context, *LoginData) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedClientHandlingServiceServer) mustEmbedUnimplementedClientHandlingServiceServer() {}
func (UnimplementedClientHandlingServiceServer) testEmbeddedByValue()                               {}

// UnsafeClientHandlingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientHandlingServiceServer will
// result in compilation errors.
type UnsafeClientHandlingServiceServer interface {
	mustEmbedUnimplementedClientHandlingServiceServer()
}

func RegisterClientHandlingServiceServer(s grpc.ServiceRegistrar, srv ClientHandlingServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientHandlingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientHandlingService_ServiceDesc, srv)
}

func _ClientHandlingService_SignUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SingUpData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientHandlingServiceServer).SignUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientHandlingService_SignUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientHandlingServiceServer).SignUp(ctx, req.(*SingUpData))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientHandlingService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientHandlingServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientHandlingService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientHandlingServiceServer).Login(ctx, req.(*LoginData))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientHandlingService_ServiceDesc is the grpc.ServiceDesc for ClientHandlingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientHandlingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "castmer.ClientHandlingService",
	HandlerType: (*ClientHandlingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUp",
			Handler:    _ClientHandlingService_SignUp_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ClientHandlingService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "castmer.proto",
}
