// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: subscription.proto

package subscriptionservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribtionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	UserLastname  string                 `protobuf:"bytes,2,opt,name=UserLastname,proto3" json:"UserLastname,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=UserEmail,proto3" json:"UserEmail,omitempty"`
	UserPlan      string                 `protobuf:"bytes,4,opt,name=UserPlan,proto3" json:"UserPlan,omitempty"`
	DayStart      string                 `protobuf:"bytes,5,opt,name=DayStart,proto3" json:"DayStart,omitempty"`
	DayEnd        string                 `protobuf:"bytes,6,opt,name=DayEnd,proto3" json:"DayEnd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribtionData) Reset() {
	*x = SubscribtionData{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribtionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribtionData) ProtoMessage() {}

func (x *SubscribtionData) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribtionData.ProtoReflect.Descriptor instead.
func (*SubscribtionData) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribtionData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SubscribtionData) GetUserLastname() string {
	if x != nil {
		return x.UserLastname
	}
	return ""
}

func (x *SubscribtionData) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *SubscribtionData) GetUserPlan() string {
	if x != nil {
		return x.UserPlan
	}
	return ""
}

func (x *SubscribtionData) GetDayStart() string {
	if x != nil {
		return x.DayStart
	}
	return ""
}

func (x *SubscribtionData) GetDayEnd() string {
	if x != nil {
		return x.DayEnd
	}
	return ""
}

type SubscribtionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribtionResponse) Reset() {
	*x = SubscribtionResponse{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribtionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribtionResponse) ProtoMessage() {}

func (x *SubscribtionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribtionResponse.ProtoReflect.Descriptor instead.
func (*SubscribtionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribtionResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\fsubscription\"\xc0\x01\n" +
	"\x10SubscribtionData\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\"\n" +
	"\fUserLastname\x18\x02 \x01(\tR\fUserLastname\x12\x1c\n" +
	"\tUserEmail\x18\x03 \x01(\tR\tUserEmail\x12\x1a\n" +
	"\bUserPlan\x18\x04 \x01(\tR\bUserPlan\x12\x1a\n" +
	"\bDayStart\x18\x05 \x01(\tR\bDayStart\x12\x16\n" +
	"\x06DayEnd\x18\x06 \x01(\tR\x06DayEnd\"2\n" +
	"\x14SubscribtionResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse2h\n" +
	"\x15ClientHandlingService\x12O\n" +
	"\tSubscribe\x12\x1e.subscription.SubscribtionData\x1a\".subscription.SubscribtionResponseB\x17Z\x15./subscriptionserviceb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscription_proto_goTypes = []any{
	(*SubscribtionData)(nil),     // 0: subscription.SubscribtionData
	(*SubscribtionResponse)(nil), // 1: subscription.SubscribtionResponse
}
var file_subscription_proto_depIdxs = []int32{
	0, // 0: subscription.ClientHandlingService.Subscribe:input_type -> subscription.SubscribtionData
	1, // 1: subscription.ClientHandlingService.Subscribe:output_type -> subscription.SubscribtionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
