// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: subscription.proto

package subscriptionservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientHandlingService_Subscribe_FullMethodName = "/subscription.ClientHandlingService/Subscribe"
)

// ClientHandlingServiceClient is the client API for ClientHandlingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientHandlingServiceClient interface {
	Subscribe(ctx context.Context, in *SubscribtionData, opts ...grpc.CallOption) (*SubscribtionResponse, error)
}

type clientHandlingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientHandlingServiceClient(cc grpc.ClientConnInterface) ClientHandlingServiceClient {
	return &clientHandlingServiceClient{cc}
}

func (c *clientHandlingServiceClient) Subscribe(ctx context.Context, in *SubscribtionData, opts ...grpc.CallOption) (*SubscribtionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribtionResponse)
	err := c.cc.Invoke(ctx, ClientHandlingService_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientHandlingServiceServer is the server API for ClientHandlingService service.
// All implementations must embed UnimplementedClientHandlingServiceServer
// for forward compatibility.
type ClientHandlingServiceServer interface {
	Subscribe(context.Context, *SubscribtionData) (*SubscribtionResponse, error)
	mustEmbedUnimplementedClientHandlingServiceServer()
}

// UnimplementedClientHandlingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientHandlingServiceServer struct{}

func (UnimplementedClientHandlingServiceServer) Subscribe(context.Context, *SubscribtionData) (*SubscribtionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedClientHandlingServiceServer) mustEmbedUnimplementedClientHandlingServiceServer() {}
func (UnimplementedClientHandlingServiceServer) testEmbeddedByValue()                               {}

// UnsafeClientHandlingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientHandlingServiceServer will
// result in compilation errors.
type UnsafeClientHandlingServiceServer interface {
	mustEmbedUnimplementedClientHandlingServiceServer()
}

func RegisterClientHandlingServiceServer(s grpc.ServiceRegistrar, srv ClientHandlingServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientHandlingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientHandlingService_ServiceDesc, srv)
}

func _ClientHandlingService_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribtionData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientHandlingServiceServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientHandlingService_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientHandlingServiceServer).Subscribe(ctx, req.(*SubscribtionData))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientHandlingService_ServiceDesc is the grpc.ServiceDesc for ClientHandlingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientHandlingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscription.ClientHandlingService",
	HandlerType: (*ClientHandlingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _ClientHandlingService_Subscribe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscription.proto",
}
